name: Python CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r development.txt
    - name: Lint with flake8
      run: |
        flake8 src tes
    - name: Check formatting with black
      run: |
        black --check src tes
    - name: Run tests with pytest
      run: |
        pytest tes --cov=src
