name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest

    - name: Lint with flake8
      run: |
        
        flake8 src tes

    - name: Check formatting with black
      run: |
        # Corrected path from 'tests' to 'tes'
        black --check src tes

    - name: Run tests with pytest
      run: |
        # Only run if test files exist
        if [ -d "tes" ]; then
          pytest tes
        else
          echo "Test directory 'tes' not found. Skipping tests."
        fi
